version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'azardb'
#       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'Admin123'
       MYSQL_ROOT_PASSWORD: 'Admin123'
    volumes:
       - /Users/alamalhoda/Projects/MYSQL_DATA:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  web:
#    build: .
#    image: py3.9-dj
    image: azarsarmaye:3
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /Users/alamalhoda/Projects/AzarSaryame/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db