# Generated by Django 3.2.9 on 2021-12-26 11:29

import api.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, help_text='شماره موبایل', max_length=11, null=True, verbose_name='تلفن همراه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('can_add_user', 'میتواند کاربر جدید ایجاد کند'),),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly', models.BooleanField(default=True, verbose_name='پرداخت سود ماهانه')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('id_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره حساب')),
                ('sheba', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت')),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('presenter_percent', models.IntegerField(blank=True, null=True)),
                ('get_profit', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_to_presenter', models.BooleanField(blank=True, null=True)),
                ('self_presenter', models.BooleanField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن منزل')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن اداره')),
                ('mobile1', models.CharField(blank=True, max_length=11, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('presenter_2', models.IntegerField(blank=True, null=True)),
                ('presenter_percent_2', models.IntegerField(blank=True, null=True)),
                ('self_presenter_2', models.BooleanField(blank=True, null=True)),
                ('two_step_verification', models.BooleanField(default=False, verbose_name='ورود دو مرحله ای با استفاده از پیامک')),
                ('state', django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('stuff_added', 'stuff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], default='START', max_length=50, verbose_name='مرحله در گردش کار')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bank', verbose_name='بانک')),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.city', verbose_name='محل تولد')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city', verbose_name='شهر')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moarefi_shode_ha', to='api.profile', verbose_name='معرف')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
                'permissions': (('can_add_profile_for_self', 'ایجاد پروفایل برای خودش'), ('can_add_profile_for_all', 'ایجاد پروفایل برای دیگران'), ('view_all_profiles', ' مشاهده همه پروفایل ها'), ('can_edit_profile_for_self', 'ویرایش پروفایل خودش'), ('can_edit_profile_for_all', 'ویرایش پروفایل دیگران'), ('can_delete_profile_for_all', 'حذف پروفایل'), ('can_change_profile_wf_state_for_all', 'میتواند مرحله گردش کار پروفایل را برای دیگران تغییر دهد'), ('WF_TRANSITION_PROFILE_START_TO_CONVERTED', '  گردش کار پروفایل از شروع به کانورت شده'), ('WF_TRANSITION_PROFILE_START_TO_STUFF_ADDED', 'گردش کار پروفایل از شروع به افزوده شده توسط کارمند'), ('WF_TRANSITION_PROFILE_START_TO_CUSTOMER_ADDED', 'گردش کار پروفایل از شروع به افزوده شده توسط مشتری'), ('WF_TRANSITION_PROFILE_CONVERTED_TO_STUFF_ADDED', 'گردش کار پروفایل از کانورت شده به افزوده شده توسط کارمند'), ('WF_TRANSITION_PROFILE_STUFF_ADDED_TO_STUFF_ADDED', 'گردش کار پروفایل از افزوده شده توسط کارمند به افزوده شده توسط کارمند (عدم تایید توسط مشتری)'), ('WF_TRANSITION_PROFILE_STUFF_ADDED_TO_COSTUMER_CONFIRMED', 'گردش کار پروفایل از افزوده شده توسط کارمند به تایید شده توسط مشتری'), ('WF_TRANSITION_PROFILE_COSTUMER_ADDED_TO_COSTUMER_ADDED', 'گردش کار پروفایل از افزوده شده توسط مشتری به افزوده شده توسط مشتری(عدم تایید توسط کارمند)'), ('WF_TRANSITION_PROFILE_COSTUMER_ADDED_TO_STUFF_CONFIRMED', 'گردش کار پروفایل از افزوده شده توسط مشتری به تایید توسط کارمند')),
            },
        ),
        migrations.CreateModel(
            name='ProfitKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('Tarikh_Moaser', models.CharField(max_length=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتهای قرارداد')),
                ('Tarikh_Moaser_Moaref', models.CharField(max_length=10)),
                ('presenter_effective_date', models.DateField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('NahveyePardakht', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Tbl_Pardakht_List_id', models.IntegerField(blank=True, null=True)),
                ('percent', models.IntegerField()),
                ('DarMelyoon_Moaref', models.IntegerField(blank=True, null=True)),
                ('contract_term', models.SmallIntegerField(blank=True, null=True, verbose_name='مدت قرارداد')),
                ('state', django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('stuff_added', 'stuff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], default='start', max_length=50, protected=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام دیگر')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_create_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_date'],
                'permissions': (('view_all_transactions', 'مشاهده همه تراکنش ها'), ('add_transaction_for_all', 'ایجاد تراکنش برای دیگران'), ('can_change_transaction_wf_state_for_all', 'میتواند مرحله گردش کار تراکنش را برای دیگران تغییر دهد'), ('WF_TRANSITION_TRANSACTION_START_TO_CONVERTED', 'گردش کار تراکنش از شروع به به کانورت شده'), ('WF_TRANSITION_TRANSACTION_START_TO_STUFF_ADDED', 'گردش کار تراکنش از شروع به افزوده شده توسط کارمند'), ('WF_TRANSITION_TRANSACTION_START_TO_CUSTOMER_ADDED', 'گردش کار تراکنش از شروع به افزوده شده توسط مشتری'), ('WF_TRANSITION_TRANSACTION_CONVERTED_TO_STUFF_ADDED', 'گردش کار تراکنش از کانورت شده به افزوده شده توسط کارمند'), ('WF_TRANSITION_TRANSACTION_STUFF_ADDED_TO_STUFF_ADDED', 'گردش کار تراکنش از افزوده شده توسط کارمند به افزوده شده توسط کارمند (عدم تایید توسط مشتری)'), ('WF_TRANSITION_TRANSACTION_STUFF_ADDED_TO_COSTUMER_CONFIRMED', 'گردش کار تراکنش از افزوده شده توسط کارمند به تایید شده توسط مشتری'), ('WF_TRANSITION_TRANSACTION_COSTUMER_ADDED_TO_COSTUMER_ADDED', 'گردش کار تراکنش از افزوده شده توسط مشتری به افزوده شده توسط مشتری(عدم تایید توسط کارمند)'), ('WF_TRANSITION_TRANSACTION_COSTUMER_ADDED_TO_STUFF_CONFIRMED', 'گردش کار تراکنش از افزوده شده توسط مشتری به تایید توسط کارمند'), ('WF_TRANSITION_TRANSACTION_COSTUMER_CONFIRMED_TO_BOSS_CONFIRMED', 'گردش کار تراکنش از تایید شده توسط مشتری به تایید شده توسط مدیر'), ('WF_TRANSITION_TRANSACTION_STUFF_CONFIRMED_TO_BOSS_CONFIRMED', 'گردش کار تراکنش از تایید شده توسط کارمند به تایید شده توسط مدیر')),
            },
        ),
        migrations.CreateModel(
            name='TransactionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نوع تراکنش')),
                ('description', models.TextField(verbose_name='توضیح')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRequestKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(verbose_name='توضیح')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مراحل گردش کار',
                'verbose_name_plural': 'مراحل گردش کار',
                'permissions': (('START_WF_STATE', 'مرحله شروع در گردش کار'), ('CONVERTED_WF_STATE', 'مرحله کانورت شده در گردش کار'), ('STUFF_ADDED_WF_STATE', 'مرحله اضافه شده توسط کارمند در گردش کار'), ('CUSTOMER_ADDED_WF_STATE', 'مرحله اضافه شده توسط مشتری در گردش کار'), ('STUFF_CHECKED_WF_STATE', 'مرحله بررسی شده توسط کارمند در گردش کار'), ('STUFF_CONFIRMED_WF_STATE', 'مرحله تایید شده توسط کارمند در گردش کار'), ('CUSTOMER_CONFIRMED_WF_STATE', 'مرحله تایید شده توسط مشتری در گردش کار'), ('BOSS_CONFIRMED_WF_STATE', 'مرحله تایید شده توسط مدیر عامل در گردش کار')),
            },
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactionrequestkind')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
            options={
                'permissions': (('view_all_TransactionRequests', 'مشاهده همه درخواست های مربوط به تراکنش ها'), ('add_TransactionRequests_for_others', 'ایجاد درخواست مربوط به تراکنش برای دیگران')),
            },
        ),
        migrations.CreateModel(
            name='Transaction_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactionkind', verbose_name='نوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عملیات مالی(واریز/برداشت)',
                'verbose_name_plural': 'عملیات مالی(واریز/برداشت)',
                'permissions': (('can_add_transaction_for_self', 'میتواند برای خودش تراکنش ثبت کند'), ('can_add_transaction_for_all', 'میتواند برای دیگران تراکنش ثبت کند'), ('can_view_transaction_for_all', 'میتواند تراکنش دیگران را مشاهده کند')),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.transactionkind'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.profile'),
        ),
        migrations.CreateModel(
            name='ProfitCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='از تاریخ')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('days', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد روز')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درصد')),
                ('calculated_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ سود محاسبه شده')),
                ('balance', models.BooleanField(default=False, verbose_name='تسویه شده است')),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profitkind')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiteCalculates', to='api.profile')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates', to='api.transaction', verbose_name='تراکنش متناظر')),
                ('transaction_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculate', to='api.transaction', verbose_name='تسویه شده با تراکنش')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProfileImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagekind')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_images', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی؟')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('az', models.PositiveBigIntegerField()),
                ('ta', models.PositiveBigIntegerField()),
                ('percent', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pelekans', to='api.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to=api.models.get_storage_path)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_create_by', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagekind')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر ها',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='api.province'),
        ),
    ]
