# Generated by Django 3.2.6 on 2021-08-27 03:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, help_text='شماره موبایل', max_length=11, null=True, verbose_name='تلفن همراه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ashkhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lname', models.CharField(blank=True, max_length=100, null=True)),
                ('CodeMeli', models.CharField(blank=True, max_length=10, null=True)),
                ('Adress', models.CharField(blank=True, max_length=100, null=True)),
                ('ShomareKart', models.CharField(blank=True, max_length=100, null=True)),
                ('Hesab', models.CharField(blank=True, max_length=100, null=True)),
                ('Mizan_Har_Melyoon', models.IntegerField(blank=True, null=True)),
                ('Mizan_Har_Melyoon_Moaref', models.IntegerField(blank=True, null=True)),
                ('Daryaft_Sood', models.BooleanField(blank=True, null=True)),
                ('Des', models.CharField(blank=True, max_length=100, null=True)),
                ('VarizBeMoaref', models.BooleanField(blank=True, null=True)),
                ('MorefiBekhod', models.BooleanField(blank=True, null=True)),
                ('Tel', models.CharField(blank=True, max_length=20, null=True)),
                ('Moaref_Tbl_Ashkhas_id2', models.IntegerField(blank=True, null=True)),
                ('Mizan_Har_Melyoon_Moaref2', models.IntegerField(blank=True, null=True)),
                ('MorefiBekhod2', models.BooleanField(blank=True, null=True)),
                ('Moaref_Tbl_Ashkhas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moarefi_shode_ha', to='api.ashkhas', verbose_name='معرف')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نوع تراکنش')),
                ('description', models.TextField(verbose_name='توضیح')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_by', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactionkind', verbose_name='نوع')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عملیات مالی(واریز/برداشت)',
                'verbose_name_plural': 'عملیات مالی(واریز/برداشت)',
                'permissions': (('can_add_transaction_for_self', 'میتواند برای خودش تراکنش ثبت کند'), ('can_add_transaction_for_all', 'میتواند برای دیگران تراکنش ثبت کند'), ('can_view_transaction_for_all', 'میتواند تراکنش دیگران را مشاهده کند')),
            },
        ),
        migrations.CreateModel(
            name='Tarakonesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.CharField(max_length=10)),
                ('Tarikh_Moaser', models.CharField(max_length=10)),
                ('Tarikh_Moaser_Moaref', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
                ('Mablagh', models.BigIntegerField()),
                ('NahveyePardakht', models.CharField(blank=True, max_length=40, null=True)),
                ('Des', models.TextField(blank=True, null=True)),
                ('Tbl_Pardakht_List_id', models.IntegerField(blank=True, null=True)),
                ('DarMelyoon', models.IntegerField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactionkind')),
                ('shakhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ashkhas')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='از تاریخ')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('days', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد روز')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درصد')),
                ('calculated_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ سود محاسبه شده')),
                ('balance', models.BooleanField(default=False, verbose_name='تسویه شده است')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculate', to='api.transaction', verbose_name='تراکنش متناظر')),
                ('transaction_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates', to='api.transaction', verbose_name='تسویه شده با تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی؟')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
