# Generated by Django 3.2.6 on 2021-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarakonesh',
            name='Des',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
