# Generated by Django 3.2.9 on 2021-12-27 19:45

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionrequest',
            options={'permissions': (('view_all_TransactionRequests', 'مشاهده همه درخواست های مربوط به تراکنش ها'), ('add_TransactionRequests_for_others', 'ایجاد درخواست مربوط به تراکنش برای دیگران'), ('WF_TRANSITION_TRANSACTION_REQUEST_START_TO_CUSTOMER_ADDED', 'گردش کار درخواست روی تراکنش از شروع به افزوده شده توسط مشتری'), ('WF_TRANSITION_TRANSACTION_REQUEST_CUSTOMER_ADDED_TO_STUFF_CHECKED', 'گردش کار درخواست روی تراکنش از افزوده شده توسط مشتری به بررسی شده توسط کارمند'), ('WF_TRANSITION_TRANSACTION_REQUEST_STUFF_CHECKED_TO_BOSS_CONFIRMED', 'گردش کار تراکنش از بررسی شده توسط کارمند به تایید شده توسط مدیر'))},
        ),
        migrations.AddField(
            model_name='transactionrequest',
            name='state',
            field=django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('stuff_added', 'stuff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], default='START', max_length=50, verbose_name='مرحله در گردش کار'),
        ),
    ]
