# Generated by Django 3.2.4 on 2021-06-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_add_transaction_for_self', 'میتواند برای خودش تراکنش ثبت کند'), ('can_add_transaction_for_all', 'میتواند برای دیگران تراکنش ثبت کند')), 'verbose_name': 'عملیات مالی(واریز/برداشت)', 'verbose_name_plural': 'عملیات مالی(واریز/برداشت)'},
        ),
    ]
