# Generated by Django 3.2.8 on 2021-10-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitcalculate',
            name='user',
        ),
        migrations.AlterField(
            model_name='profitcalculate',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates',
                                       to='api.transaction', verbose_name='تراکنش متناظر'),
        ),
        migrations.AlterField(
            model_name='profitcalculate',
            name='transaction_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='ProfitCalculate', to='api.transaction',
                                    verbose_name='تسویه شده با تراکنش'),
        ),
    ]
