# Generated by Django 3.2.9 on 2021-12-01 06:45

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('converted', 'converted'), ('staff_added', 'staff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('stuff_confirmed', 'stuff_confirmed'), ('boss_confirmed', 'boss_confirmed')], default='CONVERTED', max_length=50, protected=True),
        ),
    ]
