# Generated by Django 3.2.9 on 2021-12-15 12:58

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_user', 'میتواند کاربر جدید ایجاد کند'),)},
        ),
        migrations.RenameField(
            model_name='profitcalculate',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('staff_added', 'staff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], max_length=50, protected=True),
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('kind', models.CharField(choices=[('RENEW', 'تجدید'), ('REVOKE', 'ابطال'), ('CANCELLATION', 'فسخ')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
