# Generated by Django 3.2.4 on 2021-06-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_add_transaction_for_self', 'میتواند برای خودش تراکنش ثبت کند'), ('can_add_transaction_for_all', 'میتواند برای دیگران تراکنش ثبت کند'), ('can_view_transaction_for_all', 'میتواند تراکنش دیگران را مشاهده کند')), 'verbose_name': 'عملیات مالی(واریز/برداشت)', 'verbose_name_plural': 'عملیات مالی(واریز/برداشت)'},
        ),
    ]
