# Generated by Django 3.2.9 on 2021-12-27 20:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211227_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrequest',
            name='state',
            field=django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('stuff_added', 'stuff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], default='start', max_length=50, verbose_name='مرحله در گردش کار'),
        ),
    ]
