# Generated by Django 3.2.8 on 2021-10-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20211007_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelekanKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pelekan',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='kinds', to='api.pelekankind'),
        ),
    ]
