# Generated by Django 3.2.9 on 2021-12-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transactionrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRequestKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(verbose_name='توضیح')),
            ],
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactionrequestkind'),
        ),
    ]
