# Generated by Django 3.2.9 on 2021-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211215_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrequest',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
