# Generated by Django 3.2.6 on 2021-08-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tarakonesh_shakhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashkhas',
            name='Adress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
