# Generated by Django 3.2.4 on 2021-07-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_j_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='شماره موبایل', max_length=11, null=True, verbose_name='تلفن همراه'),
        ),
    ]
