# Generated by Django 3.2.8 on 2021-10-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20211007_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelekan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelekankind',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
