# Generated by Django 3.2.9 on 2021-12-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transactionrequest_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_profile', 'ایجاد پروفایل'), ('view_all_profiles', ' مشاهده همه پروفایل ها'), ('can_edit_profile_for_self', 'ویرایش پروفایل خودش'), ('can_edit_profile_for_all', 'ویرایش پروفایل دیگران'), ('can_delete_profile_for_all', 'حذف پروفایل'), ('WF_TRANSITION_PROFILE_START_TO_CONVERTED', '  گردش کار پروفایل از شروع به کانورت شده'), ('WF_TRANSITION_PROFILE_START_TO_STUFF_ADDED', 'گردش کار پروفایل از شروع به افزوده شده توسط کارمند'), ('WF_TRANSITION_PROFILE_START_TO_CUSTOMER_ADDED', 'گردش کار پروفایل از شروع به افزوده شده توسط مشتری'), ('WF_TRANSITION_PROFILE_CONVERTED_TO_STUFF_ADDED', 'گردش کار پروفایل از کانورت شده به افزوده شده توسط کارمند'), ('WF_TRANSITION_PROFILE_STUFF_ADDED_TO_STUFF_ADDED', 'گردش کار پروفایل از افزوده شده توسط کارمند به افزوده شده توسط کارمند (عدم تایید توسط مشتری)'), ('WF_TRANSITION_PROFILE_STUFF_ADDED_TO_COSTUMER_CONFIRMED', 'گردش کار پروفایل از افزوده شده توسط کارمند به تایید شده توسط مشتری'), ('WF_TRANSITION_PROFILE_COSTUMER_ADDED_TO_COSTUMER_ADDED', 'گردش کار پروفایل افزوده شده توسط مشتری به افزوده شده توسط مشتری(عدم تایید توسط کارمند)'), ('WF_TRANSITION_PROFILE_COSTUMER_ADDED_TO_STUFF_CONFIRMED', 'گردش کار پروفایل از افزوده شده توسط مشتری به تایید توسط کارمند')), 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='workflowstates',
            options={'permissions': (('START_WF_STATE', 'مرحله شروع در گردش کار'), ('CONVERTED_WF_STATE', 'مرحله کانورت شده در گردش کار'), ('STUFF_ADDED_WF_STATE', 'مرحله اضافه شده توسط کارمند در گردش کار'), ('CUSTOMER_ADDED_WF_STATE', 'مرحله اضافه شده توسط مشتری در گردش کار'), ('STUFF_CHECKED_WF_STATE', 'مرحله بررسی شده توسط کارمند در گردش کار'), ('STUFF_CONFIRMED_WF_STATE', 'مرحله تایید شده توسط کارمند در گردش کار'), ('CUSTOMER_CONFIRMED_WF_STATE', 'مرحله تایید شده توسط مشتری در گردش کار'), ('BOSS_CONFIRMED_WF_STATE', 'مرحله تایید شده توسط مدیر عامل در گردش کار')), 'verbose_name': 'مراحل گردش کار', 'verbose_name_plural': 'مراحل گردش کار'},
        ),
    ]
