# Generated by Django 3.2.8 on 2021-10-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_auto_20211007_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='moarefi_shode_ha', to='api.profile', verbose_name='معرف'),
        ),
    ]
