# Generated by Django 3.2.6 on 2021-09-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ashkhas_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarakonesh',
            name='g_tarikh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ashkhas',
            name='Moaref_Tbl_Ashkhas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ashkhas', verbose_name='معرف'),
        ),
    ]
