# Generated by Django 3.2.4 on 2021-07-02 15:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Variz', 'واریز'), ('Bardast', 'برداشت'), ('withdraw e sod', 'برداشت سود')], max_length=14, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='ProfitCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='از تاریخ')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('days', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد روز')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درصد')),
                ('calculated_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ سود محاسبه شده')),
                ('balance', models.BooleanField(default=False, verbose_name='تسویه شده است')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculate', to='api.transaction', verbose_name='تراکنش متناظر')),
                ('transaction_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates', to='api.transaction', verbose_name='تسویه شده با تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
