# Generated by Django 3.2.9 on 2021-12-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211230_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
