# Generated by Django 3.2.9 on 2022-01-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=6, verbose_name='مدت زمان قرارداد بر اساس ماه'),
        ),
    ]
