# Generated by Django 3.2.8 on 2021-10-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_presenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='DarMelyoon_Moaref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
