# Generated by Django 3.2.9 on 2021-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211218_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_term',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='مدت قرارداد'),
        ),
    ]
