# Generated by Django 3.2.6 on 2021-09-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210909_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashkhas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='tarakonesh',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarakoneshha', to='api.transactionkind'),
        ),
    ]
