# Generated by Django 3.2.8 on 2021-10-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_profile', 'ایجاد پروفایل'), ('view_all_profiles', ' مشاهده همه پروفایل ها'), ('can_edit_profile_for_self', 'ویرایش پروفایل خودش'), ('can_edit_profile_for_all', 'ویرایش پروفایل دیگران'), ('can_delete_profile_for_all', 'حذف پروفایل')), 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['effective_date'], 'permissions': (('view_all_transactions', 'مشاهده همه تراکنش ها '),)},
        ),
    ]
