# Generated by Django 3.2.9 on 2021-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_contract_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام دیگر'),
        ),
    ]
