# Generated by Django 3.2.9 on 2022-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0008_transaction_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': (('can_add_plan', 'ایجاد طرح جدید'), ('view_all_plans_active', 'مشاهده همه طرح ها [فعال و غیر فعال]'), ('view_all_plans_date', 'مشاهده همه طرح ها [در بازه و خارج از بازه]'))},
        ),
        migrations.AddField(
            model_name='plan',
            name='every_n_months',
            field=models.IntegerField(default=1, verbose_name='پرداخت سود هر چند ماه یکبار'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='سقف جذب یعنی حداکثر مبلغی که شرکت مایل است در این طرح جذب شود'),
        ),
        migrations.AddField(
            model_name='plan',
            name='visible_for',
            field=models.ManyToManyField(to='auth.Group', verbose_name='گروه هایی که میتوانند طرح را ببینند'),
        ),
    ]
