# Generated by Django 3.2.8 on 2021-10-24 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211024_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['effective_date'], 'permissions': (('view_all_transactions', 'مشاهده همه تراکنش ها '), ('add_transaction_for_all', 'میتواند برای دیگران تراکنش ثبت کند'))},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
