# Generated by Django 3.2.9 on 2021-12-24 11:30

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('stuff_added', 'stuff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], default='START', max_length=50, verbose_name='مرحله در گردش کار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('start', 'start'), ('converted', 'converted'), ('stuff_added', 'stuff_added'), ('customer_added', 'customer_added'), ('stuff_checked', 'stuff_checked'), ('stuff_confirmed', 'stuff_confirmed'), ('customer_confirmed', 'customer_confirmed'), ('boss_confirmed', 'boss_confirmed')], max_length=50, protected=True),
        ),
    ]
