# Generated by Django 3.2.9 on 2022-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220107_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': (('can_add_plan', 'ایجاد طرح جدید'), ('can_activate_deactivate_plan', 'فعال یا غیر فعال سازی طرح'), ('view_all_plans_active', 'مشاهده همه طرح ها [فعال و غیر فعال]'), ('view_all_plans_date', 'مشاهده همه طرح ها [در بازه و خارج از بازه]'))},
        ),
        migrations.AddField(
            model_name='plan',
            name='aggregate',
            field=models.BooleanField(default=True, help_text='مشخص میکند آیا محاسبه درصد سود در این طرح بر اساس مجموع واریزی های قبلی است یا بر اساس مبلغ هر سرمایه گزاری', verbose_name=' آیا تجمعی است؟'),
        ),
        migrations.AddField(
            model_name='plan',
            name='min_point',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='نقطه فرآخوان'),
        ),
    ]
