# Generated by Django 3.2.6 on 2021-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ashkhas_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('az', models.PositiveBigIntegerField()),
                ('ta', models.PositiveBigIntegerField()),
                ('dar_melyoon', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tarakonesh',
            options={'ordering': ['g_Tarikh_Moaser']},
        ),
    ]
