# Generated by Django 3.2.7 on 2021-09-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210921_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ashkhas',
            new_name='Profile',
        ),
    ]
