# Generated by Django 3.2.9 on 2022-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220108_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='monthly',
        ),
        migrations.AlterField(
            model_name='plan',
            name='aggregate',
            field=models.BooleanField(default=True, help_text='مشخص میکند آیا محاسبه درصد سود در این طرح بر اساس مجموع واریزی های قبلی است یا بر اساس مبلغ هر سرمایه گزاری', verbose_name='آیا تجمعی است؟'),
        ),
    ]
