# Generated by Django 3.2.9 on 2021-12-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211225_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_profile_for_self', 'ایجاد پروفایل برای خودش'), ('can_add_profile_for_all', 'ایجاد پروفایل برای دیگران'), ('view_all_profiles', ' مشاهده همه پروفایل ها'), ('can_edit_profile_for_self', 'ویرایش پروفایل خودش'), ('can_edit_profile_for_all', 'ویرایش پروفایل دیگران'), ('can_delete_profile_for_all', 'حذف پروفایل'), ('can_change_profile_wf_state_for_all', 'میتواند مرحله گردش کار پروفایل را برای دیگران تغییر دهد'), ('WF_TRANSITION_PROFILE_START_TO_CONVERTED', '  گردش کار پروفایل از شروع به کانورت شده'), ('WF_TRANSITION_PROFILE_START_TO_STUFF_ADDED', 'گردش کار پروفایل از شروع به افزوده شده توسط کارمند'), ('WF_TRANSITION_PROFILE_START_TO_CUSTOMER_ADDED', 'گردش کار پروفایل از شروع به افزوده شده توسط مشتری'), ('WF_TRANSITION_PROFILE_CONVERTED_TO_STUFF_ADDED', 'گردش کار پروفایل از کانورت شده به افزوده شده توسط کارمند'), ('WF_TRANSITION_PROFILE_STUFF_ADDED_TO_STUFF_ADDED', 'گردش کار پروفایل از افزوده شده توسط کارمند به افزوده شده توسط کارمند (عدم تایید توسط مشتری)'), ('WF_TRANSITION_PROFILE_STUFF_ADDED_TO_COSTUMER_CONFIRMED', 'گردش کار پروفایل از افزوده شده توسط کارمند به تایید شده توسط مشتری'), ('WF_TRANSITION_PROFILE_COSTUMER_ADDED_TO_COSTUMER_ADDED', 'گردش کار پروفایل از افزوده شده توسط مشتری به افزوده شده توسط مشتری(عدم تایید توسط کارمند)'), ('WF_TRANSITION_PROFILE_COSTUMER_ADDED_TO_STUFF_CONFIRMED', 'گردش کار پروفایل از افزوده شده توسط مشتری به تایید توسط کارمند')), 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['effective_date'], 'permissions': (('view_all_transactions', 'مشاهده همه تراکنش ها '), ('add_transaction_for_all', 'ایجاد تراکنش برای دیگران'), ('can_change_transaction_wf_state_for_all', 'میتواند مرحله گردش کار تراکنش را برای دیگران تغییر دهد'), ('WF_TRANSITION_TRANSACTION_START_TO_CONVERTED', 'گردش کار تراکنش از شروع به به کانورت شده'), ('WF_TRANSITION_TRANSACTION_START_TO_STUFF_ADDED', 'گردش کار تراکنش از شروع به افزوده شده توسط کارمند'), ('WF_TRANSITION_TRANSACTION_START_TO_CUSTOMER_ADDED', 'گردش کار تراکنش از شروع به افزوده شده توسط مشتری'), ('WF_TRANSITION_TRANSACTION_CONVERTED_TO_STUFF_ADDED', 'گردش کار تراکنش از کانورت شده به افزوده شده توسط کارمند'), ('WF_TRANSITION_TRANSACTION_STUFF_ADDED_TO_STUFF_ADDED', 'گردش کار تراکنش از افزوده شده توسط کارمند به افزوده شده توسط کارمند (عدم تایید توسط مشتری)'), ('WF_TRANSITION_TRANSACTION_STUFF_ADDED_TO_COSTUMER_CONFIRMED', 'گردش کار تراکنش از افزوده شده توسط کارمند به تایید شده توسط مشتری'), ('WF_TRANSITION_TRANSACTION_COSTUMER_ADDED_TO_COSTUMER_ADDED', 'گردش کار تراکنش از افزوده شده توسط مشتری به افزوده شده توسط مشتری(عدم تایید توسط کارمند)'), ('WF_TRANSITION_TRANSACTION_COSTUMER_ADDED_TO_STUFF_CONFIRMED', 'گردش کار تراکنش از افزوده شده توسط مشتری به تایید توسط کارمند'), ('WF_TRANSITION_TRANSACTION_COSTUMER_CONFIRMED_TO_BOSS_CONFIRMED', 'گردش کار تراکنش از تایید شده توسط مشتری به تایید شده توسط مدیر'), ('WF_TRANSITION_TRANSACTION_STUFF_CONFIRMED_TO_BOSS_CONFIRMED', 'گردش کار تراکنش از تایید شده توسط کارمند به تایید شده توسط مدیر'))},
        ),
    ]
