# Generated by Django 3.2.9 on 2021-11-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211120_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP',
            new_name='OtpCode',
        ),
    ]
