# Generated by Django 3.2.7 on 2021-09-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210928_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelekan',
            old_name='dar_melyoon',
            new_name='percent',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='VarizBeMoaref',
            new_name='charge_to_presenter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='CodeMeli',
            new_name='code_meli',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Daryaft_Sood',
            new_name='get_profit',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Mizan_Har_Melyoon',
            new_name='percent',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Moaref_Tbl_Ashkhas_id',
            new_name='presenter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Moaref_Tbl_Ashkhas_id2',
            new_name='presenter_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Mizan_Har_Melyoon_Moaref',
            new_name='presenter_percent',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Mizan_Har_Melyoon_Moaref2',
            new_name='presenter_percent_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='MorefiBekhod',
            new_name='self_presenter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='MorefiBekhod2',
            new_name='self_presenter_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Hesab',
            new_name='shomare_hesab',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ShomareKart',
            new_name='shomare_kart',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Tel',
            new_name='tel',
        ),
    ]
