# Generated by Django 3.2.7 on 2021-09-28 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210928_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactionkind', verbose_name='نوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عملیات مالی(واریز/برداشت)',
                'verbose_name_plural': 'عملیات مالی(واریز/برداشت)',
                'permissions': (('can_add_transaction_for_self', 'میتواند برای خودش تراکنش ثبت کند'), ('can_add_transaction_for_all', 'میتواند برای دیگران تراکنش ثبت کند'), ('can_view_transaction_for_all', 'میتواند تراکنش دیگران را مشاهده کند')),
            },
        ),
        migrations.CreateModel(
            name='TransactionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('Tarikh_Moaser', models.CharField(max_length=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('Tarikh_Moaser_Moaref', models.CharField(max_length=10)),
                ('presenter_effective_date', models.DateField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('NahveyePardakht', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('Tbl_Pardakht_List_id', models.IntegerField(blank=True, null=True)),
                ('percent', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_by', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarakoneshha', to='api.transactionkind')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarakoneshha', to='api.profile')),
            ],
            options={
                'ordering': ['effective_date'],
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tarakonesh',
        ),
        migrations.AlterField(
            model_name='profitcalculate',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculate', to='api.transactionnew', verbose_name='تراکنش متناظر'),
        ),
        migrations.AlterField(
            model_name='profitcalculate',
            name='transaction_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfitCalculates', to='api.transactionnew', verbose_name='تسویه شده با تراکنش'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
