# Generated by Django 3.2.7 on 2021-09-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210928_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionNew',
            new_name='Transaction',
        ),
    ]
