# Generated by Django 3.2.7 on 2021-09-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_rename_transactionnew_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile1',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='transactions_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                    to='api.transactionkind'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='transactions_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                    to='api.profile'),
        ),
    ]
