# Generated by Django 3.2.7 on 2021-09-30 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_auto_20210930_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (
            ('can_add_profile', 'ایجاد پروفایل'), ('can_edit_profile_for_self', 'ویرایش پروفایل خودش'),
            ('can_edit_profile_for_all', 'ویرایش پروفایل دیگران'), ('can_delete_profile_for_all', 'حذف پروفایل')),
                     'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
    ]
