# Generated by Django 3.2.7 on 2021-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211003_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimagekind',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileimagekind',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
