# Generated by Django 3.2.7 on 2021-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211003_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimagekind',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
