# Generated by Django 3.2.7 on 2021-10-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_family_name_profile_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImageKind',
            new_name='ImageKind',
        ),
        migrations.AddField(
            model_name='image',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagekind'),
        ),
        migrations.AlterField(
            model_name='profileimagegallery',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_images', to='api.profile'),
        ),
    ]
