# Generated by Django 3.2.7 on 2021-10-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211003_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='kind',
        ),
    ]
