# Generated by Django 3.2.7 on 2021-10-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_image_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagekind'),
        ),
    ]
